var links = [
    {id:"0", source:"1", target: "2", type: "segment"},
    {id:"1", source:"2", target: "3", type: "adjacency"},
    {id:"2", source:"3", target: "4", type: "segment"},
    {id:"3", source:"4", target: "5", type: "adjacency"},
    {id:"4", source:"5", target: "6", type: "segment"},
    {id:"5", source:"6", target: "7", type: "adjacency"},
    {id:"6", source:"7", target: "8", type: "segment"},
    {id:"7", source:"8", target: "9", type: "adjacency"},
    {id:"8", source:"9", target: "10", type: "segment"},
    {id:"9", source:"10", target: "11", type: "adjacency"},
    {id:"10", source:"11", target: "12", type: "segment"},
    {id:"11", source:"12", target: "13", type: "adjacency"},
    {id:"12", source:"13", target: "14", type: "segment"},
    {id:"13", source:"14", target: "15", type: "adjacency"},
    {id:"14", source:"15", target: "16", type: "segment"},

    {id:"15", source:"17", target: "18", type: "segment"},
    {id:"16", source:"18", target: "19", type: "adjacency"},
    {id:"17", source:"19", target: "20", type: "segment"},
    {id:"18", source:"20", target: "21", type: "adjacency"},
    {id:"19", source:"21", target: "22", type: "segment"},
    {id:"20", source:"22", target: "23", type: "adjacency"},
    {id:"21", source:"23", target: "24", type: "segment"},
    {id:"22", source:"24", target: "25", type: "adjacency"},
    {id:"23", source:"25", target: "26", type: "segment"},
    {id:"24", source:"26", target: "27", type: "adjacency"},
    {id:"25", source:"27", target: "28", type: "segment"},
    {id:"26", source:"28", target: "29", type: "adjacency"},
    {id:"27", source:"29", target: "30", type: "segment"},
    {id:"28", source:"30", target: "31", type: "adjacency"},
    {id:"29", source:"31", target: "32", type: "segment"},
    
    {id:"30", source:"1", target: "17", type: "descent"},
    {id:"31", source:"2", target: "18", type: "descent"},
    {id:"32", source:"3", target: "22", type: "descent"},
    {id:"33", source:"4", target: "21", type: "descent"},
    {id:"34", source:"5", target: "20", type: "descent"},
    {id:"35", source:"6", target: "19", type: "descent"},
    {id:"36", source:"7", target: "23", type: "descent"},
    {id:"37", source:"8", target: "24", type: "descent"},
    {id:"38", source:"9", target: "25", type: "descent"},
    {id:"39", source:"10", target: "26", type: "descent"},
    {id:"40", source:"11", target: "30", type: "descent"},
    {id:"41", source:"12", target: "29", type: "descent"},
    {id:"42", source:"13", target: "28", type: "descent"},
    {id:"43", source:"14", target: "27", type: "descent"},
    {id:"44", source:"15", target: "31", type: "descent"},
    {id:"45", source:"16", target: "32", type: "descent"},

];

var nodes = {
    "1": {name: "1", focus: "0", level: "0", end: true},
    "2": {name: "2", focus: "1", level: "0", end: false},
    "3": {name: "3", focus: "1", level: "0", end: false},
    "4": {name: "4", focus: "1", level: "0", end: false},
    "5": {name: "5", focus: "1", level: "0", end: false},
    "6": {name: "6", focus: "1", level: "0", end: false},
    "7": {name: "7", focus: "1", level: "0", end: false},
    "8": {name: "8", focus: "1", level: "0", end: false},
    "9": {name: "9", focus: "1", level: "0", end: false},
    "10": {name: "10", focus: "1", level: "0", end: false},
    "11": {name: "11", focus: "1", level: "0", end: false},
    "12": {name: "12", focus: "1", level: "0", end: false},
    "13": {name: "13", focus: "1", level: "0", end: false},
    "14": {name: "14", focus: "1", level: "0", end: false},
    "15": {name: "15", focus: "1", level: "0", end: false},
    "16": {name: "16", focus: "2", level: "0", end: true},
    "17": {name: "17", focus: "3", level: "1", end: true},
    "18": {name: "18", focus: "4", level: "1", end: false},
    "19": {name: "19", focus: "4", level: "1", end: false},
    "20": {name: "20", focus: "4", level: "1", end: false},
    "21": {name: "21", focus: "4", level: "1", end: false},
    "22": {name: "22", focus: "4", level: "1", end: false},
    "23": {name: "23", focus: "4", level: "1", end: false},
    "24": {name: "24", focus: "4", level: "1", end: false},
    "25": {name: "25", focus: "4", level: "1", end: false},
    "26": {name: "26", focus: "4", level: "1", end: false},
    "27": {name: "27", focus: "4", level: "1", end: false},
    "28": {name: "28", focus: "4", level: "1", end: false},
    "29": {name: "29", focus: "4", level: "1", end: false},
    "30": {name: "30", focus: "4", level: "1", end: false},
    "31": {name: "31", focus: "4", level: "1", end: false},
    "32": {name: "32", focus: "5", level: "1", end: true},
};
