var links = [
    {id:"0", source:"1", target: "2", type: "segment"},
    {id:"1", source:"2", target: "3", type: "adjacency"},
    {id:"2", source:"3", target: "4", type: "segment"},
    {id:"3", source:"4", target: "5", type: "adjacency"},
    {id:"4", source:"5", target: "6", type: "segment"},
    {id:"5", source:"6", target: "7", type: "adjacency"},
    {id:"6", source:"7", target: "8", type: "segment"},
    {id:"7", source:"8", target: "9", type: "adjacency"},
    {id:"8", source:"9", target: "10", type: "segment"},
    {id:"9", source:"10", target: "11", type: "adjacency"},
    {id:"10", source:"11", target: "12", type: "segment"},
    {id:"11", source:"12", target: "13", type: "adjacency"},
    {id:"12", source:"13", target: "14", type: "segment"},
    {id:"13", source:"14", target: "15", type: "adjacency"},
    {id:"14", source:"15", target: "16", type: "segment"},
    {id:"15", source:"16", target: "17", type: "adjacency"},
    {id:"16", source:"17", target: "18", type: "segment"},
    {id:"17", source:"18", target: "19", type: "adjacency"},
    {id:"18", source:"19", target: "20", type: "segment"},
    {id:"19", source:"20", target: "21", type: "adjacency"},
    {id:"20", source:"21", target: "22", type: "segment"},
    {id:"21", source:"22", target: "23", type: "adjacency"},
    {id:"22", source:"23", target: "24", type: "segment"},
    {id:"23", source:"24", target: "25", type: "adjacency"},
    {id:"24", source:"25", target: "26", type: "segment"},
    {id:"25", source:"26", target: "27", type: "adjacency"},
    {id:"26", source:"27", target: "28", type: "segment"},
    {id:"27", source:"28", target: "29", type: "adjacency"},
    {id:"28", source:"29", target: "30", type: "segment"},
    {id:"29", source:"30", target: "31", type: "adjacency"},
    {id:"30", source:"31", target: "32", type: "segment"},
    
    {id:"31", source:"33", target: "34", type: "segment"},
    {id:"32", source:"34", target: "35", type: "adjacency"},
    {id:"33", source:"35", target: "36", type: "segment"},
    {id:"34", source:"36", target: "37", type: "adjacency"},
    {id:"35", source:"37", target: "38", type: "segment"},
    {id:"36", source:"38", target: "39", type: "adjacency"},
    {id:"37", source:"39", target: "40", type: "segment"},
    {id:"38", source:"40", target: "41", type: "adjacency"},
    {id:"39", source:"41", target: "42", type: "segment"},
    {id:"40", source:"42", target: "43", type: "adjacency"},
    {id:"41", source:"43", target: "44", type: "segment"},
    {id:"42", source:"44", target: "45", type: "adjacency"},
    {id:"43", source:"45", target: "46", type: "segment"},
    {id:"44", source:"46", target: "47", type: "adjacency"},
    {id:"45", source:"47", target: "48", type: "segment"},
    {id:"46", source:"48", target: "49", type: "adjacency"},
    {id:"47", source:"49", target: "50", type: "segment"},
    {id:"48", source:"50", target: "51", type: "adjacency"},
    {id:"49", source:"51", target: "52", type: "segment"},
    {id:"50", source:"52", target: "53", type: "adjacency"},
    {id:"51", source:"53", target: "54", type: "segment"},
    {id:"52", source:"54", target: "55", type: "adjacency"},
    {id:"53", source:"55", target: "56", type: "segment"},
    {id:"54", source:"56", target: "57", type: "adjacency"},
    {id:"55", source:"57", target: "58", type: "segment"},
    {id:"56", source:"58", target: "59", type: "adjacency"},
    {id:"57", source:"59", target: "60", type: "segment"},
    {id:"58", source:"60", target: "61", type: "adjacency"},
    {id:"59", source:"61", target: "62", type: "segment"},
    {id:"60", source:"62", target: "63", type: "adjacency"},
    {id:"61", source:"63", target: "64", type: "segment"},
    
    {id:"62", source:"1", target: "33", type: "descent"},
    {id:"63", source:"2", target: "34", type: "descent"},
    {id:"64", source:"3", target: "38", type: "descent"},
    {id:"65", source:"4", target: "37", type: "descent"},
    {id:"66", source:"5", target: "36", type: "descent"},
    {id:"67", source:"6", target: "35", type: "descent"},
    {id:"68", source:"7", target: "39", type: "descent"},
    {id:"69", source:"8", target: "40", type: "descent"},
    {id:"70", source:"9", target: "41", type: "descent"},
    {id:"71", source:"10", target: "42", type: "descent"},
    {id:"72", source:"11", target: "43", type: "descent"},
    {id:"73", source:"12", target: "44", type: "descent"},
    {id:"74", source:"13", target: "45", type: "descent"},
    {id:"75", source:"14", target: "46", type: "descent"},
    {id:"76", source:"15", target: "47", type: "descent"},
    {id:"77", source:"16", target: "48", type: "descent"},
    {id:"78", source:"17", target: "57", type: "descent"},
    {id:"79", source:"18", target: "58", type: "descent"},
    {id:"80", source:"19", target: "59", type: "descent"},
    {id:"81", source:"20", target: "60", type: "descent"},
    {id:"82", source:"21", target: "61", type: "descent"},
    {id:"83", source:"22", target: "62", type: "descent"},
    {id:"84", source:"23", target: "63", type: "descent"},
    {id:"85", source:"24", target: "56", type: "descent"},
    {id:"86", source:"25", target: "55", type: "descent"},
    {id:"87", source:"26", target: "54", type: "descent"},
    {id:"88", source:"27", target: "53", type: "descent"},
    {id:"89", source:"28", target: "52", type: "descent"},
    {id:"90", source:"29", target: "51", type: "descent"},
    {id:"91", source:"30", target: "50", type: "descent"},
    {id:"92", source:"31", target: "49", type: "descent"},
    {id:"93", source:"32", target: "64", type: "descent"},
];

var nodes = {
    "1": {name: "1", focus: "0", level: "0", end: true},
    "2": {name: "2", focus: "1", level: "0", end: false},
    "3": {name: "3", focus: "1", level: "0", end: false},
    "4": {name: "4", focus: "1", level: "0", end: false},
    "5": {name: "5", focus: "1", level: "0", end: false},
    "6": {name: "6", focus: "1", level: "0", end: false},
    "7": {name: "7", focus: "1", level: "0", end: false},
    "8": {name: "8", focus: "1", level: "0", end: false},
    "9": {name: "9", focus: "1", level: "0", end: false},
    "10": {name: "10", focus: "1", level: "0", end: false},
    "11": {name: "11", focus: "1", level: "0", end: false},
    "12": {name: "12", focus: "1", level: "0", end: false},
    "13": {name: "13", focus: "1", level: "0", end: false},
    "14": {name: "14", focus: "1", level: "0", end: false},
    "15": {name: "15", focus: "1", level: "0", end: false},
    "16": {name: "16", focus: "1", level: "0", end: false},
    "17": {name: "17", focus: "1", level: "0", end: false},
    "18": {name: "18", focus: "1", level: "0", end: false},
    "19": {name: "19", focus: "1", level: "0", end: false},
    "20": {name: "20", focus: "1", level: "0", end: false},
    "21": {name: "21", focus: "1", level: "0", end: false},
    "22": {name: "22", focus: "1", level: "0", end: false},
    "23": {name: "23", focus: "1", level: "0", end: false},
    "24": {name: "24", focus: "1", level: "0", end: false},
    "25": {name: "25", focus: "1", level: "0", end: false},
    "26": {name: "26", focus: "1", level: "0", end: false},
    "27": {name: "27", focus: "1", level: "0", end: false},
    "28": {name: "28", focus: "1", level: "0", end: false},
    "29": {name: "29", focus: "1", level: "0", end: false},
    "30": {name: "30", focus: "1", level: "0", end: false},
    "31": {name: "31", focus: "1", level: "0", end: false},
    "32": {name: "32", focus: "2", level: "0", end: true},
    "33": {name: "33", focus: "3", level: "1", end: true},
    "34": {name: "34", focus: "4", level: "1", end: false},
    "35": {name: "35", focus: "4", level: "1", end: false},
    "36": {name: "36", focus: "4", level: "1", end: false},
    "37": {name: "37", focus: "4", level: "1", end: false},
    "38": {name: "38", focus: "4", level: "1", end: false},
    "39": {name: "39", focus: "4", level: "1", end: false},
    "40": {name: "40", focus: "4", level: "1", end: false},
    "41": {name: "41", focus: "4", level: "1", end: false},
    "42": {name: "42", focus: "4", level: "1", end: false},
    "43": {name: "43", focus: "4", level: "1", end: false},
    "44": {name: "44", focus: "4", level: "1", end: false},
    "45": {name: "45", focus: "4", level: "1", end: false},
    "46": {name: "46", focus: "4", level: "1", end: false},
    "47": {name: "47", focus: "4", level: "1", end: false},
    "48": {name: "48", focus: "4", level: "1", end: false},
    "49": {name: "49", focus: "4", level: "1", end: false},
    "50": {name: "50", focus: "4", level: "1", end: false},
    "51": {name: "51", focus: "4", level: "1", end: false},
    "52": {name: "52", focus: "4", level: "1", end: false},
    "53": {name: "53", focus: "4", level: "1", end: false},
    "54": {name: "54", focus: "4", level: "1", end: false},
    "55": {name: "55", focus: "4", level: "1", end: false},
    "56": {name: "56", focus: "4", level: "1", end: false},
    "57": {name: "57", focus: "4", level: "1", end: false},
    "58": {name: "58", focus: "4", level: "1", end: false},
    "59": {name: "59", focus: "4", level: "1", end: false},
    "60": {name: "60", focus: "4", level: "1", end: false},
    "61": {name: "61", focus: "4", level: "1", end: false},
    "62": {name: "62", focus: "4", level: "1", end: false},
    "63": {name: "63", focus: "4", level: "1", end: false},
    "64": {name: "64", focus: "5", level: "1", end: true},
};
