var links = [
    {source:"1", target: "2", type: "segment"},
    {source:"2", target: "3", type: "adjacency"},
    {source:"3", target: "4", type: "segment"},
    {source:"4", target: "5", type: "adjacency"},
    {source:"5", target: "6", type: "segment"},
    {source:"6", target: "7", type: "adjacency"},
    {source:"7", target: "8", type: "segment"},
    {source:"8", target: "9", type: "adjacency"},
    {source:"9", target: "10", type: "segment"},
    {source:"10", target: "11", type: "adjacency"},
    {source:"11", target: "12", type: "segment"},
    {source:"12", target: "13", type: "adjacency"},
    {source:"13", target: "14", type: "segment"},
    {source:"14", target: "15", type: "adjacency"},
    {source:"15", target: "16", type: "segment"},
    {source:"16", target: "17", type: "adjacency"},
    {source:"17", target: "18", type: "segment"},
    {source:"18", target: "19", type: "adjacency"},
    {source:"19", target: "20", type: "segment"},
    {source:"20", target: "21", type: "adjacency"},
    {source:"21", target: "22", type: "segment"},
    {source:"22", target: "23", type: "adjacency"},
    {source:"23", target: "24", type: "segment"},
    {source:"24", target: "25", type: "adjacency"},
    {source:"25", target: "26", type: "segment"},
    {source:"26", target: "27", type: "adjacency"},
    {source:"27", target: "28", type: "segment"},
    {source:"28", target: "29", type: "adjacency"},
    {source:"29", target: "30", type: "segment"},
    {source:"30", target: "31", type: "adjacency"},
    {source:"31", target: "32", type: "segment"},
    
    {source:"33", target: "34", type: "segment"},
    {source:"34", target: "35", type: "adjacency"},
    {source:"35", target: "36", type: "segment"},
    {source:"36", target: "37", type: "adjacency"},
    {source:"37", target: "38", type: "segment"},
    {source:"38", target: "39", type: "adjacency"},
    {source:"39", target: "40", type: "segment"},
    {source:"40", target: "41", type: "adjacency"},
    {source:"41", target: "42", type: "segment"},
    {source:"42", target: "43", type: "adjacency"},
    {source:"43", target: "44", type: "segment"},
    {source:"44", target: "45", type: "adjacency"},
    {source:"45", target: "46", type: "segment"},
    {source:"46", target: "47", type: "adjacency"},
    {source:"47", target: "48", type: "segment"},
    {source:"48", target: "49", type: "adjacency"},
    {source:"49", target: "50", type: "segment"},
    {source:"50", target: "51", type: "adjacency"},
    {source:"51", target: "52", type: "segment"},
    {source:"52", target: "53", type: "adjacency"},
    {source:"53", target: "54", type: "segment"},
    {source:"54", target: "55", type: "adjacency"},
    {source:"55", target: "56", type: "segment"},
    {source:"56", target: "57", type: "adjacency"},
    {source:"57", target: "58", type: "segment"},
    {source:"58", target: "59", type: "adjacency"},
    {source:"59", target: "60", type: "segment"},
    {source:"60", target: "61", type: "adjacency"},
    {source:"61", target: "62", type: "segment"},
    {source:"62", target: "63", type: "adjacency"},
    {source:"63", target: "64", type: "segment"},
    
    {source:"1", target: "33", type: "descent"},
    {source:"2", target: "34", type: "descent"},
    {source:"3", target: "38", type: "descent"},
    {source:"4", target: "37", type: "descent"},
    {source:"5", target: "36", type: "descent"},
    {source:"6", target: "35", type: "descent"},
    {source:"7", target: "39", type: "descent"},
    {source:"8", target: "40", type: "descent"},
    {source:"9", target: "41", type: "descent"},
    {source:"10", target: "42", type: "descent"},
    {source:"11", target: "43", type: "descent"},
    {source:"12", target: "44", type: "descent"},
    {source:"13", target: "45", type: "descent"},
    {source:"14", target: "46", type: "descent"},
    {source:"15", target: "47", type: "descent"},
    {source:"16", target: "48", type: "descent"},
    {source:"17", target: "57", type: "descent"},
    {source:"18", target: "58", type: "descent"},
    {source:"19", target: "59", type: "descent"},
    {source:"20", target: "60", type: "descent"},
    {source:"21", target: "61", type: "descent"},
    {source:"22", target: "62", type: "descent"},
    {source:"23", target: "63", type: "descent"},
    {source:"24", target: "56", type: "descent"},
    {source:"25", target: "55", type: "descent"},
    {source:"26", target: "54", type: "descent"},
    {source:"27", target: "53", type: "descent"},
    {source:"28", target: "52", type: "descent"},
    {source:"29", target: "51", type: "descent"},
    {source:"30", target: "50", type: "descent"},
    {source:"31", target: "49", type: "descent"},
    {source:"32", target: "64", type: "descent"},
];

var nodes = {
    "1": {name: "1", focus: "0", level: "0", end: true},
    "2": {name: "2", focus: "1", level: "0", end: false},
    "3": {name: "3", focus: "1", level: "0", end: false},
    "4": {name: "4", focus: "1", level: "0", end: false},
    "5": {name: "5", focus: "1", level: "0", end: false},
    "6": {name: "6", focus: "1", level: "0", end: false},
    "7": {name: "7", focus: "1", level: "0", end: false},
    "8": {name: "8", focus: "1", level: "0", end: false},
    "9": {name: "9", focus: "1", level: "0", end: false},
    "10": {name: "10", focus: "1", level: "0", end: false},
    "11": {name: "11", focus: "1", level: "0", end: false},
    "12": {name: "12", focus: "1", level: "0", end: false},
    "13": {name: "13", focus: "1", level: "0", end: false},
    "14": {name: "14", focus: "1", level: "0", end: false},
    "15": {name: "15", focus: "1", level: "0", end: false},
    "16": {name: "16", focus: "1", level: "0", end: false},
    "17": {name: "17", focus: "1", level: "0", end: false},
    "18": {name: "18", focus: "1", level: "0", end: false},
    "19": {name: "19", focus: "1", level: "0", end: false},
    "20": {name: "20", focus: "1", level: "0", end: false},
    "21": {name: "21", focus: "1", level: "0", end: false},
    "22": {name: "22", focus: "1", level: "0", end: false},
    "23": {name: "23", focus: "1", level: "0", end: false},
    "24": {name: "24", focus: "1", level: "0", end: false},
    "25": {name: "25", focus: "1", level: "0", end: false},
    "26": {name: "26", focus: "1", level: "0", end: false},
    "27": {name: "27", focus: "1", level: "0", end: false},
    "28": {name: "28", focus: "1", level: "0", end: false},
    "29": {name: "29", focus: "1", level: "0", end: false},
    "30": {name: "30", focus: "1", level: "0", end: false},
    "31": {name: "31", focus: "1", level: "0", end: false},
    "32": {name: "32", focus: "2", level: "0", end: true},
    "33": {name: "33", focus: "3", level: "1", end: true},
    "34": {name: "34", focus: "4", level: "1", end: false},
    "35": {name: "35", focus: "4", level: "1", end: false},
    "36": {name: "36", focus: "4", level: "1", end: false},
    "37": {name: "37", focus: "4", level: "1", end: false},
    "38": {name: "38", focus: "4", level: "1", end: false},
    "39": {name: "39", focus: "4", level: "1", end: false},
    "40": {name: "40", focus: "4", level: "1", end: false},
    "41": {name: "41", focus: "4", level: "1", end: false},
    "42": {name: "42", focus: "4", level: "1", end: false},
    "43": {name: "43", focus: "4", level: "1", end: false},
    "44": {name: "44", focus: "4", level: "1", end: false},
    "45": {name: "45", focus: "4", level: "1", end: false},
    "46": {name: "46", focus: "4", level: "1", end: false},
    "47": {name: "47", focus: "4", level: "1", end: false},
    "48": {name: "48", focus: "4", level: "1", end: false},
    "49": {name: "49", focus: "4", level: "1", end: false},
    "50": {name: "50", focus: "4", level: "1", end: false},
    "51": {name: "51", focus: "4", level: "1", end: false},
    "52": {name: "52", focus: "4", level: "1", end: false},
    "53": {name: "53", focus: "4", level: "1", end: false},
    "54": {name: "54", focus: "4", level: "1", end: false},
    "55": {name: "55", focus: "4", level: "1", end: false},
    "56": {name: "56", focus: "4", level: "1", end: false},
    "57": {name: "57", focus: "4", level: "1", end: false},
    "58": {name: "58", focus: "4", level: "1", end: false},
    "59": {name: "59", focus: "4", level: "1", end: false},
    "60": {name: "60", focus: "4", level: "1", end: false},
    "61": {name: "61", focus: "4", level: "1", end: false},
    "62": {name: "62", focus: "4", level: "1", end: false},
    "63": {name: "63", focus: "4", level: "1", end: false},
    "64": {name: "64", focus: "5", level: "1", end: true},
};