var links = [
    {source:"1", target: "2", type: "segment"},
    {source:"2", target: "3", type: "adjacency"},
    {source:"3", target: "4", type: "segment"},
    {source:"4", target: "5", type: "adjacency"},
    {source:"5", target: "6", type: "segment"},
    {source:"6", target: "7", type: "adjacency"},
    {source:"7", target: "8", type: "segment"},
    {source:"8", target: "9", type: "adjacency"},
    {source:"9", target: "10", type: "segment"},
    {source:"10", target: "11", type: "adjacency"},
    {source:"11", target: "12", type: "segment"},
    {source:"12", target: "13", type: "adjacency"},
    {source:"13", target: "14", type: "segment"},
    {source:"14", target: "15", type: "adjacency"},
    {source:"15", target: "16", type: "segment"},

    {source:"17", target: "18", type: "segment"},
    {source:"18", target: "19", type: "adjacency"},
    {source:"19", target: "20", type: "segment"},
    {source:"20", target: "21", type: "adjacency"},
    {source:"21", target: "22", type: "segment"},
    {source:"22", target: "23", type: "adjacency"},
    {source:"23", target: "24", type: "segment"},
    {source:"24", target: "25", type: "adjacency"},
    {source:"25", target: "26", type: "segment"},
    {source:"26", target: "27", type: "adjacency"},
    {source:"27", target: "28", type: "segment"},
    {source:"28", target: "29", type: "adjacency"},
    {source:"29", target: "30", type: "segment"},
    {source:"30", target: "31", type: "adjacency"},
    {source:"31", target: "32", type: "segment"},
    
    {source:"1", target: "17", type: "descent"},
    {source:"2", target: "18", type: "descent"},
    {source:"3", target: "22", type: "descent"},
    {source:"4", target: "21", type: "descent"},
    {source:"5", target: "20", type: "descent"},
    {source:"6", target: "19", type: "descent"},
    {source:"7", target: "23", type: "descent"},
    {source:"8", target: "24", type: "descent"},
    {source:"9", target: "25", type: "descent"},
    {source:"10", target: "26", type: "descent"},
    {source:"11", target: "30", type: "descent"},
    {source:"12", target: "29", type: "descent"},
    {source:"13", target: "28", type: "descent"},
    {source:"14", target: "27", type: "descent"},
    {source:"15", target: "31", type: "descent"},
    {source:"16", target: "32", type: "descent"},

];

var nodes = {
    "1": {name: "1", group: "0", level: "0", end: true},
    "2": {name: "2", group: "1", level: "0", end: false},
    "3": {name: "3", group: "1", level: "0", end: false},
    "4": {name: "4", group: "1", level: "0", end: false},
    "5": {name: "5", group: "1", level: "0", end: false},
    "6": {name: "6", group: "1", level: "0", end: false},
    "7": {name: "7", group: "1", level: "0", end: false},
    "8": {name: "8", group: "1", level: "0", end: false},
    "9": {name: "9", group: "1", level: "0", end: false},
    "10": {name: "10", group: "1", level: "0", end: false},
    "11": {name: "11", group: "1", level: "0", end: false},
    "12": {name: "12", group: "1", level: "0", end: false},
    "13": {name: "13", group: "1", level: "0", end: false},
    "14": {name: "14", group: "1", level: "0", end: false},
    "15": {name: "15", group: "1", level: "0", end: false},
    "16": {name: "16", group: "2", level: "0", end: true},
    "17": {name: "17", group: "3", level: "1", end: true},
    "18": {name: "18", group: "4", level: "1", end: false},
    "19": {name: "19", group: "4", level: "1", end: false},
    "20": {name: "20", group: "4", level: "1", end: false},
    "21": {name: "21", group: "4", level: "1", end: false},
    "22": {name: "22", group: "4", level: "1", end: false},
    "23": {name: "23", group: "4", level: "1", end: false},
    "24": {name: "24", group: "4", level: "1", end: false},
    "25": {name: "25", group: "4", level: "1", end: false},
    "26": {name: "26", group: "4", level: "1", end: false},
    "27": {name: "27", group: "4", level: "1", end: false},
    "28": {name: "28", group: "4", level: "1", end: false},
    "29": {name: "29", group: "4", level: "1", end: false},
    "30": {name: "30", group: "4", level: "1", end: false},
    "31": {name: "31", group: "4", level: "1", end: false},
    "32": {name: "32", group: "5", level: "1", end: true},
};