var links = [
    {source:"1", target: "2", type: "segment"},
    {source:"2", target: "3", type: "adjacency"},
    {source:"3", target: "4", type: "segment"},
    {source:"4", target: "5", type: "adjacency"},
    {source:"5", target: "6", type: "segment"},
    {source:"6", target: "7", type: "adjacency"},
    {source:"7", target: "8", type: "segment"},
    {source:"8", target: "9", type: "adjacency"},
    {source:"9", target: "10", type: "segment"},
    {source:"10", target: "11", type: "adjacency"},
    {source:"11", target: "12", type: "segment"},
    {source:"12", target: "13", type: "adjacency"},
    {source:"13", target: "14", type: "segment"},
    {source:"14", target: "15", type: "adjacency"},
    {source:"15", target: "16", type: "segment"},
    {source:"16", target: "17", type: "adjacency"},
    {source:"17", target: "18", type: "segment"},
    {source:"18", target: "19", type: "adjacency"},
    {source:"19", target: "20", type: "segment"},
    {source:"20", target: "21", type: "adjacency"},
    {source:"21", target: "22", type: "segment"},
    {source:"22", target: "23", type: "adjacency"},
    {source:"23", target: "24", type: "segment"},
    {source:"24", target: "25", type: "adjacency"},
    {source:"25", target: "26", type: "segment"},
    {source:"26", target: "27", type: "adjacency"},
    {source:"27", target: "28", type: "segment"},
    {source:"28", target: "29", type: "adjacency"},
    {source:"29", target: "30", type: "segment"},
    {source:"30", target: "31", type: "adjacency"},
    {source:"31", target: "32", type: "segment"},
    {source:"32", target: "33", type: "adjacency"},
    {source:"33", target: "34", type: "segment"},
    {source:"34", target: "35", type: "adjacency"},
    {source:"35", target: "36", type: "segment"},
    {source:"36", target: "37", type: "adjacency"},
    {source:"37", target: "38", type: "segment"},
    {source:"38", target: "39", type: "adjacency"},
    {source:"39", target: "40", type: "segment"},
    {source:"40", target: "41", type: "adjacency"},
    {source:"41", target: "42", type: "segment"},
    {source:"42", target: "43", type: "adjacency"},
    {source:"43", target: "44", type: "segment"},
    {source:"44", target: "45", type: "adjacency"},
    {source:"45", target: "46", type: "segment"},
    {source:"46", target: "47", type: "adjacency"},
    {source:"47", target: "48", type: "segment"},
    {source:"48", target: "49", type: "adjacency"},
    {source:"49", target: "50", type: "segment"},
    {source:"50", target: "51", type: "adjacency"},
    {source:"51", target: "52", type: "segment"},
    {source:"52", target: "53", type: "adjacency"},
    {source:"53", target: "54", type: "segment"},
    {source:"54", target: "55", type: "adjacency"},
    {source:"55", target: "56", type: "segment"},
    {source:"56", target: "57", type: "adjacency"},
    {source:"57", target: "58", type: "segment"},
    {source:"58", target: "59", type: "adjacency"},
    {source:"59", target: "60", type: "segment"},
    {source:"60", target: "61", type: "adjacency"},
    {source:"61", target: "62", type: "segment"},
    {source:"62", target: "63", type: "adjacency"},
    {source:"63", target: "64", type: "segment"},
    
    {source:"65", target: "66", type: "segment" },
    {source:"66", target: "67", type: "adjacency" },
    {source:"67", target: "68", type: "segment" },
    {source:"68", target: "69", type: "adjacency" },
    {source:"69", target: "70", type: "segment" },
    {source:"70", target: "71", type: "adjacency" },
    {source:"71", target: "72", type: "segment" },
    {source:"72", target: "73", type: "adjacency" },
    {source:"73", target: "74", type: "segment" },
    {source:"74", target: "75", type: "adjacency" },
    {source:"75", target: "76", type: "segment" },
    {source:"76", target: "77", type: "adjacency" },
    {source:"77", target: "78", type: "segment" },
    {source:"78", target: "79", type: "adjacency" },
    {source:"79", target: "80", type: "segment" },
    {source:"80", target: "81", type: "adjacency" },
    {source:"81", target: "82", type: "segment" },
    {source:"82", target: "83", type: "adjacency" },
    {source:"83", target: "84", type: "segment" },
    {source:"84", target: "85", type: "adjacency" },
    {source:"85", target: "86", type: "segment" },
    {source:"86", target: "87", type: "adjacency" },
    {source:"87", target: "88", type: "segment" },
    {source:"88", target: "89", type: "adjacency" },
    {source:"89", target: "90", type: "segment" },
    {source:"90", target: "91", type: "adjacency" },
    {source:"91", target: "92", type: "segment" },
    {source:"92", target: "93", type: "adjacency" },
    {source:"93", target: "94", type: "segment" },
    {source:"94", target: "95", type: "adjacency" },
    {source:"95", target: "96", type: "segment" },
    {source:"96", target: "97", type: "adjacency" },
    {source:"97", target: "98", type: "segment" },
    {source:"98", target: "99", type: "adjacency" },
    {source:"99", target: "100", type: "segment" },
    {source:"100", target: "101", type: "adjacency" },
    {source:"101", target: "102", type: "segment" },
    {source:"102", target: "103", type: "adjacency" },
    {source:"103", target: "104", type: "segment" },
    {source:"104", target: "105", type: "adjacency" },
    {source:"105", target: "106", type: "segment" },
    {source:"106", target: "107", type: "adjacency" },
    {source:"107", target: "108", type: "segment" },
    {source:"108", target: "109", type: "adjacency" },
    {source:"109", target: "110", type: "segment" },
    {source:"110", target: "111", type: "adjacency" },
    {source:"111", target: "112", type: "segment" },
    {source:"112", target: "113", type: "adjacency" },
    {source:"113", target: "114", type: "segment" },
    {source:"114", target: "115", type: "adjacency" },
    {source:"115", target: "116", type: "segment" },
    {source:"116", target: "117", type: "adjacency" },
    {source:"117", target: "118", type: "segment" },
    {source:"118", target: "119", type: "adjacency" },
    {source:"119", target: "120", type: "segment" },
    {source:"120", target: "121", type: "adjacency" },
    {source:"121", target: "122", type: "segment" },
    {source:"122", target: "123", type: "adjacency" },
    {source:"123", target: "124", type: "segment" },
    {source:"124", target: "125", type: "adjacency" },
    {source:"125", target: "126", type: "segment" },
    {source:"126", target: "127", type: "adjacency" },
    {source:"127", target: "128", type: "segment" },

    {source:"1", target: "97", type: "descent"},
    {source:"2", target: "98", type: "descent"},
    {source:"3", target: "102", type: "descent"},
    {source:"4", target: "101", type: "descent"},
    {source:"5", target: "100", type: "descent"},
    {source:"6", target: "99", type: "descent"},
    {source:"7", target: "103", type: "descent"},
    {source:"8", target: "104", type: "descent"},
    {source:"9", target: "105", type: "descent"},
    {source:"10", target: "106", type: "descent"},
    {source:"11", target: "107", type: "descent"},
    {source:"12", target: "108", type: "descent"},
    {source:"13", target: "109", type: "descent"},
    {source:"14", target: "110", type: "descent"},
    {source:"15", target: "111", type: "descent"},
    {source:"16", target: "112", type: "descent"},
    {source:"17", target: "121", type: "descent"},
    {source:"18", target: "122", type: "descent"},
    {source:"19", target: "123", type: "descent"},
    {source:"20", target: "124", type: "descent"},
    {source:"21", target: "125", type: "descent"},
    {source:"22", target: "126", type: "descent"},
    {source:"23", target: "127", type: "descent"},
    {source:"24", target: "120", type: "descent"},
    {source:"25", target: "119", type: "descent"},
    {source:"26", target: "118", type: "descent"},
    {source:"27", target: "117", type: "descent"},
    {source:"28", target: "116", type: "descent"},
    {source:"29", target: "115", type: "descent"},
    {source:"30", target: "114", type: "descent"},
    {source:"31", target: "113", type: "descent"},
    {source:"32", target: "128", type: "descent"},
    {source:"33", target: "65", type: "descent"},
    {source:"34", target: "66", type: "descent"},
    {source:"35", target: "67", type: "descent"},
    {source:"36", target: "68", type: "descent"},
    {source:"37", target: "69", type: "descent"},
    {source:"38", target: "70", type: "descent"},
    {source:"39", target: "71", type: "descent"},
    {source:"40", target: "72", type: "descent"},
    {source:"41", target: "73", type: "descent"},
    {source:"42", target: "74", type: "descent"},
    {source:"43", target: "75", type: "descent"},
    {source:"44", target: "76", type: "descent"},
    {source:"45", target: "77", type: "descent"},
    {source:"46", target: "78", type: "descent"},
    {source:"47", target: "79", type: "descent"},
    {source:"48", target: "88", type: "descent"},
    {source:"49", target: "87", type: "descent"},
    {source:"50", target: "86", type: "descent"},
    {source:"51", target: "85", type: "descent"},
    {source:"52", target: "84", type: "descent"},
    {source:"53", target: "83", type: "descent"},
    {source:"54", target: "82", type: "descent"},
    {source:"55", target: "81", type: "descent"},
    {source:"56", target: "80", type: "descent"},
    {source:"57", target: "89", type: "descent"},
    {source:"58", target: "90", type: "descent"},
    {source:"59", target: "91", type: "descent"},
    {source:"60", target: "92", type: "descent"},
    {source:"61", target: "93", type: "descent"},
    {source:"62", target: "94", type: "descent"},
    {source:"63", target: "95", type: "descent"},
    {source:"64", target: "96", type: "descent"},
];

var nodes = {
    "1": {name: "1", focus: "0", level: "0", end: true},
    "2": {name: "2", focus: "1", level: "0", end: false},
    "3": {name: "3", focus: "1", level: "0", end: false},
    "4": {name: "4", focus: "1", level: "0", end: false},
    "5": {name: "5", focus: "1", level: "0", end: false},
    "6": {name: "6", focus: "1", level: "0", end: false},
    "7": {name: "7", focus: "1", level: "0", end: false},
    "8": {name: "8", focus: "1", level: "0", end: false},
    "9": {name: "9", focus: "1", level: "0", end: false},
    "10": {name: "10", focus: "1", level: "0", end: false},
    "11": {name: "11", focus: "1", level: "0", end: false},
    "12": {name: "12", focus: "1", level: "0", end: false},
    "13": {name: "13", focus: "1", level: "0", end: false},
    "14": {name: "14", focus: "1", level: "0", end: false},
    "15": {name: "15", focus: "1", level: "0", end: false},
    "16": {name: "16", focus: "1", level: "0", end: false},
    "17": {name: "17", focus: "1", level: "0", end: false},
    "18": {name: "18", focus: "1", level: "0", end: false},
    "19": {name: "19", focus: "1", level: "0", end: false},
    "20": {name: "20", focus: "1", level: "0", end: false},
    "21": {name: "21", focus: "1", level: "0", end: false},
    "22": {name: "22", focus: "1", level: "0", end: false},
    "23": {name: "23", focus: "1", level: "0", end: false},
    "24": {name: "24", focus: "1", level: "0", end: false},
    "25": {name: "25", focus: "1", level: "0", end: false},
    "26": {name: "26", focus: "1", level: "0", end: false},
    "27": {name: "27", focus: "1", level: "0", end: false},
    "28": {name: "28", focus: "1", level: "0", end: false},
    "29": {name: "29", focus: "1", level: "0", end: false},
    "30": {name: "30", focus: "1", level: "0", end: false},
    "31": {name: "31", focus: "1", level: "0", end: false},
    "32": {name: "32", focus: "1", level: "0", end: false},
    "33": {name: "33", focus: "1", level: "0", end: false},
    "34": {name: "34", focus: "1", level: "0", end: false},
    "35": {name: "35", focus: "1", level: "0", end: false},
    "36": {name: "36", focus: "1", level: "0", end: false},
    "37": {name: "37", focus: "1", level: "0", end: false},
    "38": {name: "38", focus: "1", level: "0", end: false},
    "39": {name: "39", focus: "1", level: "0", end: false},
    "40": {name: "40", focus: "1", level: "0", end: false},
    "41": {name: "41", focus: "1", level: "0", end: false},
    "42": {name: "42", focus: "1", level: "0", end: false},
    "43": {name: "43", focus: "1", level: "0", end: false},
    "44": {name: "44", focus: "1", level: "0", end: false},
    "45": {name: "45", focus: "1", level: "0", end: false},
    "46": {name: "46", focus: "1", level: "0", end: false},
    "47": {name: "47", focus: "1", level: "0", end: false},
    "48": {name: "48", focus: "1", level: "0", end: false},
    "49": {name: "49", focus: "1", level: "0", end: false},
    "50": {name: "50", focus: "1", level: "0", end: false},
    "51": {name: "51", focus: "1", level: "0", end: false},
    "52": {name: "52", focus: "1", level: "0", end: false},
    "53": {name: "53", focus: "1", level: "0", end: false},
    "54": {name: "54", focus: "1", level: "0", end: false},
    "55": {name: "55", focus: "1", level: "0", end: false},
    "56": {name: "56", focus: "1", level: "0", end: false},
    "57": {name: "57", focus: "1", level: "0", end: false},
    "58": {name: "58", focus: "1", level: "0", end: false},
    "59": {name: "59", focus: "1", level: "0", end: false},
    "60": {name: "60", focus: "1", level: "0", end: false},
    "61": {name: "61", focus: "1", level: "0", end: false},
    "62": {name: "62", focus: "1", level: "0", end: false},
    "63": {name: "63", focus: "1", level: "0", end: false},
    "64": {name: "64", focus: "2", level: "0", end: true},
    "65": {name: "65", focus: "3", level: "1", end: true},
    "66": {name: "66", focus: "4", level: "1", end: false},
    "67": {name: "67", focus: "4", level: "1", end: false},
    "68": {name: "68", focus: "4", level: "1", end: false},
    "69": {name: "69", focus: "4", level: "1", end: false},
    "70": {name: "70", focus: "4", level: "1", end: false},
    "71": {name: "71", focus: "4", level: "1", end: false},
    "72": {name: "72", focus: "4", level: "1", end: false},
    "73": {name: "73", focus: "4", level: "1", end: false},
    "74": {name: "74", focus: "4", level: "1", end: false},
    "75": {name: "75", focus: "4", level: "1", end: false},
    "76": {name: "76", focus: "4", level: "1", end: false},
    "77": {name: "77", focus: "4", level: "1", end: false},
    "78": {name: "78", focus: "4", level: "1", end: false},
    "79": {name: "79", focus: "4", level: "1", end: false},
    "80": {name: "80", focus: "4", level: "1", end: false},
    "81": {name: "81", focus: "4", level: "1", end: false},
    "82": {name: "82", focus: "4", level: "1", end: false},
    "83": {name: "83", focus: "4", level: "1", end: false},
    "84": {name: "84", focus: "4", level: "1", end: false},
    "85": {name: "85", focus: "4", level: "1", end: false},
    "86": {name: "86", focus: "4", level: "1", end: false},
    "87": {name: "87", focus: "4", level: "1", end: false},
    "88": {name: "88", focus: "4", level: "1", end: false},
    "89": {name: "89", focus: "4", level: "1", end: false},
    "90": {name: "90", focus: "4", level: "1", end: false},
    "91": {name: "91", focus: "4", level: "1", end: false},
    "92": {name: "92", focus: "4", level: "1", end: false},
    "93": {name: "93", focus: "4", level: "1", end: false},
    "94": {name: "94", focus: "4", level: "1", end: false},
    "95": {name: "95", focus: "4", level: "1", end: false},
    "96": {name: "96", focus: "4", level: "1", end: false},
    "97": {name: "97", focus: "4", level: "1", end: false},
    "98": {name: "98", focus: "4", level: "1", end: false},
    "99": {name: "99", focus: "4", level: "1", end: false},
    "100": {name: "100", focus: "4", level: "1", end: false},
    "101": {name: "101", focus: "4", level: "1", end: false},
    "102": {name: "102", focus: "4", level: "1", end: false},
    "103": {name: "103", focus: "4", level: "1", end: false},
    "104": {name: "104", focus: "4", level: "1", end: false},
    "105": {name: "105", focus: "4", level: "1", end: false},
    "106": {name: "106", focus: "4", level: "1", end: false},
    "107": {name: "107", focus: "4", level: "1", end: false},
    "108": {name: "108", focus: "4", level: "1", end: false},
    "109": {name: "109", focus: "4", level: "1", end: false},
    "110": {name: "110", focus: "4", level: "1", end: false},
    "111": {name: "111", focus: "4", level: "1", end: false},
    "112": {name: "112", focus: "4", level: "1", end: false},
    "113": {name: "113", focus: "4", level: "1", end: false},
    "114": {name: "114", focus: "4", level: "1", end: false},
    "115": {name: "115", focus: "4", level: "1", end: false},
    "116": {name: "116", focus: "4", level: "1", end: false},
    "117": {name: "117", focus: "4", level: "1", end: false},
    "118": {name: "118", focus: "4", level: "1", end: false},
    "119": {name: "119", focus: "4", level: "1", end: false},
    "120": {name: "120", focus: "4", level: "1", end: false},
    "121": {name: "121", focus: "4", level: "1", end: false},
    "122": {name: "122", focus: "4", level: "1", end: false},
    "123": {name: "123", focus: "4", level: "1", end: false},
    "124": {name: "124", focus: "4", level: "1", end: false},
    "125": {name: "125", focus: "4", level: "1", end: false},
    "126": {name: "126", focus: "4", level: "1", end: false},
    "127": {name: "127", focus: "4", level: "1", end: false},
    "128": {name: "128", focus: "5", level: "1", end: true},
};